definitions:
  controller.Article:
    properties:
      created_by:
        type: string
      id:
        type: integer
      modified_by:
        type: string
    type: object
info:
  contact:
    name: shicli
  description: This is gin
  title: gin first
  version: "1.0"
paths:
  /api/auth/register:
    post:
      parameters:
      - description: 名字
        in: query
        name: Name
        type: string
      - description: 密码
        in: query
        name: Password
        type: string
      - description: 电话
        in: query
        name: Telemetry
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/controller.Article'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 注册信息
swagger: "2.0"
